# Generated by Django 3.2.15 on 2023-06-28 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='cordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deparment_cordinator', to='grader.staff'),
        ),
    ]
