# Generated by Django 3.2.15 on 2023-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='signature',
            field=models.FileField(upload_to='staff/signatures/'),
        ),
    ]
