# Generated by Django 3.2.15 on 2023-06-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_alter_department_cordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(default='CPE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='short_name',
            field=models.CharField(default='SEET', max_length=50),
            preserve_default=False,
        ),
    ]
