# Generated by Django 3.2.15 on 2023-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_alter_staff_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='staff/signatures/'),
        ),
    ]
