# Generated by Django 3.2.15 on 2023-06-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_auto_20230629_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='grader.faculty'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(choices=[('Prof', 'Prof'), ('Assitant Prof', 'Assitant Prof'), ('Dr', 'Dr'), ('Engr', 'Engr'), ('Mr', 'Mr'), ('Mrs', 'Mrs')], max_length=50),
        ),
    ]
