# Generated by Django 3.2.15 on 2023-06-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_auto_20230629_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='secret',
            field=models.TextField(default='Secret', help_text='Text used to validate the use of signature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
