# Generated by Django 3.2.15 on 2023-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_auto_20230710_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalyearsession',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
