# Generated by Django 3.2.15 on 2023-07-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_finalyearsession_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='co_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_projects', to='grader.staff'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='grader.staff'),
        ),
    ]
