# Generated by Django 3.2.15 on 2023-06-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_auto_20230630_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_projects', to='grader.faculty'),
        ),
    ]
