# Generated by Django 3.2.15 on 2023-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0006_auto_20230713_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cordinator_approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Approved', 'Not Approved')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Not Approved', 'Not Approved')], default='Pending', max_length=20),
        ),
    ]
