# Generated by Django 3.2.15 on 2023-07-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0007_auto_20230702_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='session',
            field=models.ForeignKey(default='dbcfc2ce-5aa2-4baa-80e1-1537ed546768', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='grader.finalyearsession'),
            preserve_default=False,
        ),
    ]
