# Generated by Django 3.2.15 on 2023-10-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_internaldefense_device_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='external_defense_score',
            field=models.IntegerField(blank=True, help_text='This is the average of 3 external defense scores', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hardware_software_score',
            field=models.IntegerField(blank=True, help_text='This is the score given to the student device (Hardware/Software integration)', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_defense_score',
            field=models.IntegerField(blank=True, help_text='This is the average of 3 internal defense scores', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='project_score',
            field=models.IntegerField(blank=True, help_text='This is the Average score of all 4 scores category', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='proposal_score',
            field=models.IntegerField(blank=True, help_text='This is the average of 3 proposal grading scores', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='supervisor_score',
            field=models.IntegerField(blank=True, help_text="This is the score given to a student's project by their supervisor", null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='work_progress_score',
            field=models.IntegerField(blank=True, help_text='This is the average of 3 project work progress scores', null=True),
        ),
    ]
