# Generated by Django 3.2.15 on 2023-12-21 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0011_auto_20231031_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hardware', models.IntegerField(blank=True, null=True)),
                ('software', models.IntegerField()),
                ('packaging', models.IntegerField()),
                ('functionality', models.IntegerField()),
                ('simulation', models.IntegerField()),
                ('total', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_evaluated', models.DateField()),
                ('signed', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_grading', to='grader.department')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_product_scores', to='grader.staff')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_grading', to='grader.faculty')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_grading', to='grader.project')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_grading', to='grader.finalyearsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_scores', to='grader.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
