# Generated by Django 3.2.15 on 2023-12-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0012_productevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productevaluation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
